stacked-git/stgit

stgit/commands/pull.py
stgit/commands/refresh.py
stgit/config.py
stgit/git.py
stgit/lib/git.py
stgit/lib/transaction.py
t/t1200-push-modified.sh
t/t5000-refresh-submodules.sh
t/t6000-config.sh

When refreshing patches, the default action is to include every path
which is changed relative to the current working directory. This common
workflow creates problems when one uses a submodule. Due to the nature
of submodules, under some workflows they can often be out-of-sync, such
as when working on new updates within a submodule.
Accidental refreshes which include the submodule changes often occur,
which leads to commits which unintentionally include changes to
submodule pointers. These commits likely cause submodules to point to
incorrect locations.
Since it is not easy to convince many developers to always use "refresh
--index", instead, modify the default refresh behavior.
Instead of including all files, now check to make sure that we exclude
submodule files.
We can do this by using …

refresh: do not include submodules by default

---

stgit/commands/export.py
stgit/git.py

When exporting, we now open the patch files with explicit utf-8 encoding.
Without explicitly choosing the encoding, it defaults to the locale
encoding which is C/ASCII in the test environment.
We similarly use utf-8 encoding when opening patch files to be applied
(i.e. for `stg sync`).
Signed-off-by: Peter Grayson <jpgrayson@gmail.com>

Repair t2000-sync regression

---

setup.py
stgit/compat.py
stgit/run.py
tox.ini

With this dict comprehension replaced, unit tests pass with Python 2.6.
Repairs #13.
Signed-off-by: Peter Grayson <jpgrayson@gmail.com>

Replace dict comprehension for Python 2.6 support

---

stgit/commands/common.py
stgit/compat.py
t/t1800-import.sh

It is possible for emails to specify a utf-8 charset, but erroneously
contain latin-1 encoded characters. Reference:
https://lkml.org/lkml/2018/1/24/704
Instead of failing import with a decoding error, stgit now takes the same
approach as git by decoding non-utf8 bytes as latin-1.
Signed-off-by: Peter Grayson <jpgrayson@gmail.com>

Handle utf-8 email bodies with latin-1 characters

---

stgit/commands/common.py
t/t1800-import.sh
t/t1800-import/email-quoted-from

Although not clearly RFC-2047 compliant, there are cases in the wild where
email headers contain encoded words within quotes. E.g.:
From: "=?UTF-8?q?Christian=20K=C3=B6nig?=" <name@example.com>
Python2 and Python3 have different behavior when parsing such a header
using email.header.decode_words(). Python3 will decode the encoded words
between the quotes whereas Python2 will leave the encoded words in their
encoded state. The goal for this change is to make Python2 behave as
Python3.
A regular expression (email.header.ecre) is used in
email.header.decode_header() to detect and parse encoded words. This regex
is subtly different between Python2 and Python3--the Python2 regex requires
whitespace or the end-of-string after encoded words whereas Python3 does
not. Monkey-patching the Python2 …

Decode email headers with quoted encoded words

---

.travis.yml
Makefile

Add a `.travis.yml` file to allow stgit to be tested using the Travis-CI service. This uses Travis' containerized environments (as opposed to the slower VM environments). The tests cover nine python versions from 2.6 through 3.7 (nightly), including pypy and pypy3.
We capture code coverage data during the python 2.7 and python 3.6 tests. That coverage data is uploaded to the Coveralls service which tracks code coverage over time as well as providing a web-based view of coverage over individual files.
The test and coverage outcomes for my fork can be seen here:
- https://travis-ci.org/jpgrayson/stgit
- https://coveralls.io/github/jpgrayson/stgit
If this PR is accepted, I would also propose enabling Travis-CI and Coveralls on the upstream `ctmarinas/stgit` repo. In addition to performing …

Travis-CI and Coveralls

---

stgit/commands/publish.py
t/t4100-publish.sh

This option is useful for 'github style'
pull requests where it is often requested
to rewrite your pull request multiple
times before it is accepted.

Add --overwrite option for publish.

---

stgit/commands/log.py

I didn't know about the existence of the `log --clear` command and
finally stumbled over it.  This extra description will give future
travelers a heads-up to the existence of this useful command.

Add "clear" to log command description

---

completion/stgit.zsh
stgit/commands/mail.py

The default message ID generation in the Python email library will use the
system hostname as the domain part. This adds an option to override
this (for Python versions that support it), to avoid leaking the system
hostname into the sent messages.

Add 'domain' parameter to 'mail' command

---

stgit/out.py

Maybe this is good enough for now to close #35.
By changing .info() and .note() to stderr, we can slacken the isatty() restriction and get away with no test breakages. Seems fairly clean; though of course this is still a change in behavior that might break fragile scripts.

out.py: prefer stderr and remove isatty() restriction

---

stgit/commands/common.py
stgit/commands/edit.py
stgit/commands/refresh.py
stgit/lib/git/repository.py
stgit/lib/stack.py
t/t1200-push-modified.sh
t/t1208-push-and-pop.sh
t/t1302-repair-interop.sh
t/t2200-rebase.sh
t/t2600-squash.sh
t/t2700-refresh.sh
t/t3300-edit.sh

Three more or less random commits:
- Resetting of the committer information on stg refresh and edit to bring it in line with 'git commit --ammend'.
- A change in newline at the end of the commit message. This makes it similar to git and also allows the test suite to pass on Mac OS X where sed -i always adds a newline and the end of the modified file.
- Support for 'git notes'. They are now preserved on refresh/push/pop/edit. The 'squash' and 'pick' commands do not handle git notes (maybe in a future patch but these create new patches without old commit information).
Please feel free to cherry-pick whichever patches you find appropriate or comment on whatever is missing/wrong.

Proposed (RFC)

---

Documentation/tutorial.txt

An important part of the workflow is cleaning up stgit information from branches that you no longer want to manage with stgit.
This adds mention of that in the tutorial.

Add mention of --cleanup and --delete in tutorial

---

stgit/commands/float.py

The `stg float` command will push a patch to a top which is the current patch which does not include unapplied patches.
This adds mentions that in the help text.

Clarify top for float command is current

---

stgit/commands/pick.py
stgit/config.py
t/t3401-pick-commit.sh

Config options "stgit.pick.prepend" and "stgit.pick.append" defines
format strings for 'git show --pretty'.
Option 'stgit.pick.prepend' inserts lines after commit subject.
Default is stgit.pick.append = 'format:(imported from commit %H)'.
Signed-off-by: Konstantin Khlebnikov <khlebnikov@yandex-team.ru>

Add config options for specifiing text added by 'pick --expose'

---

completion/stgit.zsh
stgit/commands/refresh.py
t/t2704-refresh-spill.sh

In case a user wants to completely change what goes into the patch, they can run `stg refresh --spill` and then manually add/refresh files/changes back into the patch.
I feel like `stgit` currently lacks any easy way to achieve this.
This functionality closely mirrors what `git-delouse` script does:
[GitToolkit/GitDelouse](https://github.com/nvie/git-toolbelt#git-delouse)

Add "--spill" option to the refresh command that spills the content of the revision into worktree and empties its patch

---

stgit/run.py

In Python 3, the env argument to Popen has to be a dict of strings, see
https://bugzilla.mozilla.org/show_bug.cgi?id=1585258#c4
This is important when running under Windows, where the unicode strings
are processed directly by the subprocess C code.
However, under posix systems the environment variables are serialized to
bytes using the file system encoding, which may not support unicode
characters.
This means that passing bytes as environment variables and skipping the
encoding is mandatory on posix in order to support unicode environment
variables.
Therefore skip encoding when on Windows.
Fixes: #79

Pass environment variables to Popen as dict of strings

---

t/t1001-branch-rename.sh

Attempted to cover reported issue where hidden patches were causing issues with renames. (Issue  #68)

test(branch --rename): Clean up and add tests to cover issue #68

---

stgit/commands/pull.py
t/t1210-pull-check-upstream.sh

bug(#83): fix stg pull when no upstream is configured

---

stgit/lib/git/iw.py

CLOSES #85 
Adding `--add` to `git update-index` to make sure temporary index update does not crash when newly added files are present

bug(#85): fix refresh crashes when index contains added files and path limiting

---

stgit/commands/series.py
stgit/config.py
t/t0008-series.sh

Add a configuration parameter `stg.series.description` which, when set
to `yes` will always show the description in `stg series`.
With this enabled, users may pass `--no-description` to hide
descriptions in the output.
Resolves #88

stg series: add option to always show description

---

stgit/commands/refresh.py
t/t7504-commit-msg-hook.sh

Add a `--diff` flag to `stg refresh` that, when used with `--edit`, is
equivalent to `stg edit --diff`.
Resolves #98

refresh: Support --diff with --edit

---

stgit/utils.py
t/t2703-refresh-pre-commit-hook.sh

Git 2.9 made it easier to share hooks with the team by adding a `core.hooksPath` setting.
This change removes the hard-coded ".git/hooks" location (which is still the default though).
See also: https://git-scm.com/docs/git-config#Documentation/git-config.txt-corehooksPath

Add support for core.hooksPath

---

stgit/commands/mail.py
t/t1900-mail.sh

- Fixes the issue described here: https://github.com/stacked-git/stgit/issues/104 
- Adds a test case to avoid regressions

"stg mail": always include the first commit in the cover letter stats

---

stgit/commands/squash.py

Resolves #71.
This change makes stgit's squash commit edit message mirror git's.
[![asciicast](https://asciinema.org/a/uke1YRL44VOAOqHkUmcqxItS3.svg)](https://asciinema.org/a/uke1YRL44VOAOqHkUmcqxItS3)
New edit message example:
```
foo
bar
baz
```

Rearchitect squash edit message to include all commits.

---

stgit/commands/squash.py

After using this in practice, I think that having the patch number
followed by the patch name is more readable. With this change it's
easier to scan the commit message to determine where each change
ends and the next one begins.
Before:
After:
I recognize that this PR is more personal preference; it's not the end
of the world if we leave it as-is.

Reorder squash message to ease readibility.

---

stgit/commands/squash.py

Include 'name' in squash's edit message.
If --name isn't included we don't try to guess what the name may be
(since the name is dependent on the commit description the user gives to
the squashed commit.
Tested locally that this works correctly with and without '--name'.
[![asciicast](https://asciinema.org/a/qZb3YV9KwN95zctV1QnLnuQQZ.svg)](https://asciinema.org/a/qZb3YV9KwN95zctV1QnLnuQQZ)
Resolves #119

Include 'name' in squash's edit message.

---

stgit/commands/squash.py

I observed an issue locally where if a commit message does not include a
trailing newline, the suggested commit message is more "scrunched" than
we'd like it to be -- there's no newline between the commit message and the
instructions.
This scenario is easy to get into if you perform a squash followed by
another squash onto the same patch (by default the trailing newline is 
stripped).
The fix here is to strip all newlines from the end of each commit
message and then add two newlines to the end (one to get to the next
line, another to ensure the blank line between messages).

Ensure a newline after each commit in 'stg squash'.

---

stgit/commands/common.py
stgit/commands/delete.py
stgit/commands/rebase.py
stgit/commands/squash.py
t/t2203-rebase-interactive.sh

`stg rebase --interactive` is a new tool which mirrors `git rebase --interactive`.
Using an editor `--interactive` lets the user reorder patches, squash patch chains, or delete individual patches.
[![asciicast](https://asciinema.org/a/BWJZZ65vFtlpGubobNLbixr9G.svg)](https://asciinema.org/a/BWJZZ65vFtlpGubobNLbixr9G)
Further instructions could be added but this seemed like a good base set. I've been using this locally and it helps execute certain sets of commands much faster! Tests are included.

Add --interactive option to rebase

---

stgit/commands/common.py
stgit/commands/new.py
t/t1003-new.sh
t/t1800-import.sh

Git has a great feature where you can get a 'git diff' in the editor window when
creating a commit. This can help give context while you write your commit
message.
This PR adds this functionality to 'stg new'. Just like Git, there's two ways to
trigger the new feature:
1. `stg new --verbose`
2. Setting the config setting `commit.verbose=1` (borrows Git's config var)
[![asciicast](https://asciinema.org/a/422507.svg)](https://asciinema.org/a/422507)

Add --verbose option to 'stg new'

---

stgit/commands/squash.py
t/t2600-squash.sh

This mirrors the behavior seen by Git. In git, if you exit the commit 
message editor without providing any message, the squash is aborted:
[![asciicast](https://asciinema.org/a/6T0n15zn2mVdzttSIEzttwCbO.svg)](https://asciinema.org/a/6T0n15zn2mVdzttSIEzttwCbO)
This PR brings the same functionality to stgit:
[![asciicast](https://asciinema.org/a/422492.svg)](https://asciinema.org/a/422492)
Message text:
```
$ stg squash foo bar                                                                                                                                                                                                 
Invoking the editor: "vim .stgit-squash.txt" ... done …
```

Empty 'squash' commit message aborts the squash.

---

stgit/commands/squash.py

This matches the behavior of git (in behavior and in instruction text). This
change should have been part of https://github.com/stacked-git/stgit/pull/121
but was overlooked.
[![asciicast](https://asciinema.org/a/423856.svg)](https://asciinema.org/a/423856)

Update squash instructions to include empty messages.

---

stgit/commands/__init__.py
stgit/commands/mail.py
stgit/commands/uncommit.py
stgit/utils.py

Seeing these errors when running flake8 locally:
```
make lint-flake8
./stgit/utils.py:78:47: B006 Do not use mutable data structures for argument defaults.  They are created during function definition time. All calls to the function reuse this one instance of that data structure, persisting changes between them.
./stgit/commands/mail.py:467:52: B006 Do not use mutable data structures for argument defaults.  They are created during function definition time. All calls to the function reuse this one instance of that data structure, persisting changes between them.
./stgit/commands/uncommit.py:123:13: B007 Loop control variable 'i' not used within the loop body. If this is intended, start the name with an underscore.
./stgit/commands/__init__.py:90:14: B007 Loop control variable 'mod' not …
```

Resolve 'flake8' errors.

---

examples/gitconfig
stgit/commands/rebase.py
t/t2204-rebase-autostash.sh

This mirrors a feature of 'git rebase' where, instead of erroring on a dirty
worktree, `--autostash` will stash the changes and apply them after the rebase
has completed.
I'm not sure if it's more 'stgit-ish' to create a patch or a stash. I kept the
git behavior (a stash) but I could see arguments either way.
[![asciicast](https://asciinema.org/a/423971.svg)](https://asciinema.org/a/423971)

Add --autostash to 'stg rebase'

---

t/t1009-gpg.sh

I'm seeing this error locally:
```
$ prove --timer --jobs 15 ./t[0-9]*.sh
[23:13:23] ./t1002-branch-clone.sh ............. ok     3226 ms ( 0.03 usr  0.01 sys +  6.42 cusr  1.90 csys =  8.36 CPU)
===(      87;4  5/?  8/?  0/?  0/?  5/?  6/?  9/?  7/?  0/?  8/?... )===String found where operator expected at ./t1009-gpg.sh line 3, near "echo ""
(Missing semicolon on previous line?)
Bareword found where operator expected at ./t1009-gpg.sh line 3, near "$(echo"
(Missing operator before echo?)
Bareword found where operator expected at ./t1009-gpg.sh line 3, near "$(stg"
(Missing operator before stg?)
String found where operator expected at ./t1009-gpg.sh line 3, near ")" = ""
(Missing operator before " = "?)
Bareword found where operator expected at ./t1009-gpg.sh line 3, near "" = "p2" …
```

Fix 'prove' error with bang line.

---

.gitignore

This directory appears when one runs `make coverage`. It should be ignored.

Add .cov-files to .gitignore.

---

stgit/commands/edit.py
stgit/commands/rebase.py
stgit/lib/edit.py
t/t2203-rebase-interactive.sh
t/t3300-edit.sh
t/t7504-commit-msg-hook.sh

Add 'edit' instruction to 'rebase --interactive'.
'edit' opens the interactive editor to modify the commit.
I feel safer making these changes after the test additions included in
https://github.com/stacked-git/stgit/pull/132; this PR has been tested against
those new tests. I can't figure out how to base this PR off of that PR, so that 
PR's changes are currently included in this PR as well.

Add 'edit' instruction to 'rebase --interactive'.

---

stgit/commands/common.py
stgit/commands/imprt.py
stgit/commands/new.py

When originally setting up the diff for 'stg new', I incorrectly used git's
diff. I've since realized that stgit's diff is way better! We should be using
that!
What's wrong with 'git diff' irt stgit?
- 'git diff' gives you only unstaged files
- 'git diff --cached' gives you only staged files
For 'git commit', this distinction is great (since you're about to commit the
staged files). For 'stg new' however, you're not about to make a commit at all!
Both staged and unstaged files are important.
The solution: use 'stg diff', which gives a diff of both staged and unstaged
files:
$ stg status
M  staged
M unstaged
$ stg diff
diff --git a/staged b/staged
index 5626abf..10a1890 100644
--- a/staged
+++ b/staged
@@ -1 +1 @@
-one
+oneone
diff --git a/unstaged b/unstaged
index f719efd..10650ea 100644 …

Use correct 'diff' command in 'stg new'.

---

stgit/commands/rebase.py

By default, 'coverage' can not tell that our "infinite" loops complete.
Let it know that it doesn't have to worry about branch coverage for these
loops; they are always eventually exhausted.
This follows the instructions from 
https://coverage.readthedocs.io/en/coverage-5.0/branch.html#structurally-partial-branches

Tell 'coverage' that our loops have exits.

---

CONTRIBUTING.md

See how this looks by scrolling to the bottom of https://github.com/topher200/stgit/blob/add-link-to-coverage.io-to-contributing.md/CONTRIBUTING.md

Add link to coverage.io to CONTRIBUTING.md

---

pyproject.toml

Basic coverage.py config from their docs:
https://coverage.readthedocs.io/en/coverage-5.5/config.html#syntax
I just took the default example in their docs. I really wanted to grab the
`__repr__` thing; happy to modify this as sees fit.
This PR resolves the need to manually exclude debug lines with commits such as
8e946bac5f962a9e42f17cdb4081a25b2b7459cd.

Add coverage settings to ignore debug code.

---

stgit/commands/new.py
t/t1003-new.sh

In #122, `new` got a `--verbose` flag that defaults to true if the
`commit.verbose` configuration in git is set. To determine whether the
configuration was set, the new feature used `config.getint`.
However, per the git-config documentation, `commit.verbose` can be a
boolean:
commit.verbose
A boolean or int to specify the level of verbose with git commit. See git-commit(1).
In fact, if `commit.verbose` is set to `true` right now, this will fail with,
Value for "commit.verbose" is not an integer: "true"
Given that `config.getbool` will handle both, integers and booleans, use
that to determine if the configuration is set instead. Since
`config.getbool` will return `None` if unset, default to False rather than
None.

new: commit.verbose is a boolean

---

stgit/commands/common.py
stgit/commands/imprt.py
stgit/commands/squash.py
stgit/lib/edit.py
t/t3300-edit.sh

This resolves https://github.com/stacked-git/stgit/issues/138 by...
1. Adding instruction hints on the *power* of 'stg edit'.
2. Stripping these new hint lines from the description.
3. Aborting 'stg edit' if all description lines are cleared.
From conversation on https://github.com/stacked-git/stgit/issues/138 it became
clear that aborting the 'edit' on an empty editor is correct.  This behavior
mirrors 'git commit' and 'stg squash'.
Previously, if a user cleared the 'stg edit' editor window, the patch
description would be cleared.  This is unintuative! Users likely expect that
this would abort the edit instead.
[![asciicast](https://asciinema.org/a/426044.svg)](https://asciinema.org/a/426044)

'stg edit' aborts on empty patch description; add instructions.

---

completion/stgit.zsh
stgit/completion/bash.py
stgit/completion/fish.py

If the `stg.series.description` config is set to `true`, then the output of
`stg series` always includes the first line of the commit messages.
For example,
$ stg series
+ foo # Add foo
+ bar # Rename bar
> baz # Remove baz
When the completion scripts call `stg series`, they use the full string,
including the description:
$ stg refresh -p <tab>
foo\ \#\ Add\ foo
To solve this, pass the `--no-description` flag to `stg series` in all
completion scripts when retrieving a list of patches.

completion: Add --no-description for stg series

---

t/t1003-new.sh

Add test cases to show that `stg new` does not include a diff with `--verbose`.
I expanded the existing test cases to check that there's actually a diff included in the commit message editor window for `--verbose`; I confirm there is no diff when there is no `--verbose`.

Add test case for `stg new` without `--verbose`.

---

stgit/commands/rebase.py
t/t2203-rebase-interactive.sh

'fixup' can be used to 'squash' a patch into the previous patch BUT keeping
only the base patch's commit message. It's a faster 'squash' for the times you
know you have an awesome commit message already.
[![asciicast](https://asciinema.org/a/s5IfTxhE0Yl0SrHxDN1xkZI2s.svg)](https://asciinema.org/a/s5IfTxhE0Yl0SrHxDN1xkZI2s)

'stg rebase --interactive' learns 'fixup' instruction

---

stgit/commands/common.py
stgit/commands/rebase.py
stgit/lib/transaction.py
t/t2203-rebase-interactive.sh

Pretty simple PR: 'stg rebase --interactive' learns 'hide' 
instruction to hide individual patches.
We could add an 'unhide' instruction but I haven't found 
a need for it yet!
[![asciicast](https://asciinema.org/a/HZycIMJeisCRP59mNHdZVDCgt.svg)](https://asciinema.org/a/HZycIMJeisCRP59mNHdZVDCgt)

'stg rebase --interactive' learns 'hide' instruction

---

stgit/main.py

Some systems (e.g. recent Ubuntu, Linux Mint) don't have a `python` command, but only `python2` or `python3`. This change invokes `os.system()` with the currently running interpreter, which avoids an error that occurs and is displayed when `python` is not available.

Change os.system() call to avoid invoking 'python', which isn't always available

---

Makefile
completion/Makefile

For now install bash completion.
As bash user I'm not aware where other two should be placed.
Rename script during install, name should match command.
Base bash-completion loads "$cmd", "$cmd.bash", "_$cmd" at first use.
Signed-off-by: Konstantin Khlebnikov <khlebnikov@yandex-team.ru>

Add target install-completion into Makefile

---

stgit/lib/stack.py

Fixes assertion failure which can occur because the short_name is a
truncated version of the already-sanitized long_name, but the
truncation may leave a trailing dot.

stack: strip trailing dots from short_name

---

src/argset.rs
src/cmd/diff.rs
src/cmd/export.rs
src/cmd/patches.rs
src/cmd/show.rs
src/patchedit/mod.rs
src/stupid.rs
t/t0005-show.sh
t/t0006-patches.sh
t/t2400-diff.sh
t/t4300-export.sh

Solves Issue #187
Not super-happy about adding the binary-argument to the diff_tree_patch function but if we can have an argument for `--color` I suppose we can have one for `--binary` too and it makes the handling of `--diff-opts` a lot simpler.

Multiple diff-opts

---

src/patchedit/interactive.rs

```
*  Use "patch" extension when editing a patch with a diff
It enables syntax highlighting in many editors. The file names are the
same as in the Python implementation.
```
See https://github.com/stacked-git/stgit/blob/v1.5/stgit/lib/edit.py#L105 for the Python implementation.
Tested locally by `stg edit` and `stg edit -d`.

Use "patch" extension when editing a patch with a diff

---

Cargo.lock
Cargo.toml
src/alias.rs
src/stack/stack.rs

Since 0.13, git2 has seen [many changes][1], including rust-lang/git2-rs#791
which should address the extensions.worktreeConfig issue in #195.
[1]: https://github.com/rust-lang/git2-rs/compare/0.13.0...0.15.0
The upgrade required fixing uses of [ConfigEntries][2] because it's no
longer an iterator.
However, it provides an API that lends itself well to a `while let` statement,
which provides a for-loop-like experience, so the fix was straightforward.
[2]: https://docs.rs/git2/0.15.0/git2/struct.ConfigEntries.html

Upgrade to git2 0.15

---

completion/stgit.zsh
src/argset.rs
src/cmd/completion/bash.rs
src/cmd/completion/fish.rs
src/cmd/email/format.rs
src/cmd/email/send.rs

Otherwise, `stg email send -G '--subject=Latest patch'` translates to `git send-mail '--subject=Latest' 'patch'`, and the command errors with
```
error: `git send-email`: fatal: ambiguous argument 'patch': unknown revision or path not in the working tree.
```
Also, Zsh completion reuses the current `git` completion, whatever it is. Ideally, `stg -C foo diff -D --bar -D --baz=` would complete the same as `git -C foo diff --bar --baz=`, but it's currently limited to completing the same as `git -C foo diff --baz=`, so multi-word options won't complete properly (not that they would before). If Zsh provided a companion associative array to `opt_args` that contained indices for each value represented in `opt_args`, we could filter to the current word and provide virtually perfect completion, …

Don't split passthrough options on whitespace

---

CHANGELOG.md
completion/stgit.zsh
contrib/stg-cvs
contrib/stg-gitk
contrib/stg-show
examples/gitconfig
src/cmd/email/format.rs
src/cmd/pick.rs
src/cmd/refresh.rs
src/cmd/uncommit.rs
src/commit.rs
src/patchedit/description.rs
src/patchedit/mod.rs
src/signature.rs
src/stack/transaction/builder.rs
src/stupid/mod.rs

Found via `codespell -S t -L crate,isnt,toke,swith`

docs: fix typos

---

src/hook.rs
t/t2703-refresh-pre-commit-hook.sh

In the .py => .rs rewrite, the determination of the base directory changed a bit. Before it was using the current working directory. After, it was using the .git directory instead. Both are somewhat incorrect.
According to [this
documentation](https://git-scm.com/docs/githooks/2.9.5#_description), the .git directory should be used in case the repo is a bare one. In case, the repo is a non-bare one, the root of the working tree should be used as base directory for the `core.hooksPath`.
The existing test cases (t2703-refresh-pre-commit-hook.sh) did not catch any of this, mainly because the tests did not assert whether the hooks script was actually being run at all.
This patch fixes this.

Use correct base directory for core.hooksPaths

---

Cargo.lock
Cargo.toml
src/main.rs

Previously it was necessary to build with special RUSTC_FLAGS to turn on local offset support. Now the `time` crate makes this a runtime capability that each application has to opt-in to.
----
I usually build my binaries locally and at some point must have built without activating local offsets. Since `time` v0.3.18 has a more obvious mechanism for it this PR is meant to add it to `stacked-git`.
Further, I thought I'd update to the latest `gix` for good measure, even though that isn't necessary to get local times to work.

fix: enable local-time in commits.

---

Cargo.lock

Fixes https://github.com/stacked-git/stgit/issues/306
The underlying cause of the error reported in the linked issue was a bug in `gitoxide` which got fixed in the latest release.

chore: update gix-revision, fixes #306

---

src/cmd/import.rs
t/t1800-import.sh

When importing a patch with multiple lines, the first line break in the body was removed from the body of the commit in the stack, because it was stripped when searching for the headers. Add the line break again when adding the first line to the split_message.
This did not surface in the tests, because the test bodies always had one line and the expected bodies had an incorrect number of line breaks at the end. Fix the expected number of line breaks as well.

fix(import): Keep first line break in body

---

CHANGELOG.md

While reading the changelog on the website I noticed the latest entry in the changelog says `2024-10-08`. Presumably this was a typo that was copy-pasted for the more recent entries? If you are actually from the future, feel free to close the PR 😉

Fix year in changelog (2024 -> 2023)

---

src/patch/edit/interactive.rs

gix_command by default does not pass stdin to commands. This caused editors and shells to behave weirdly. For example, vim printed a warning during opening:
Vim: Warning: Input is not from a terminal
After closing vim started this way, the terminal was messed up and needed an reset to print outputs correctly.
This is an attempt to fix stacked-git/stgit#415. It fixes the issue described there, but I can not say how it will affect other editors or even scripts. It may re-introduce some errors that 048f182a ("fix: use gix-command for interactive edit") originally tried to fix.
Closes #415

fix: Pass stdio for interactive editing

---

Cargo.lock
Cargo.toml

This update contains a security fix for
https://rustsec.org/advisories/RUSTSEC-2024-0335.html

Update gix to version 0.62

---

src/cmd/rebase.rs
t/t2203-rebase-interactive.sh

I have a stgit stack that is very old (I started it more than 10 years ago), so it has all kinds of WIP patches that I started and then did not quite finish. In several of them I have malformed patch subjects, such as multi-line titles:
$ git show -1 --pretty=%B
subsystem: fix driver
certain change
This breaks "stg rebase -i" because it expects to have one line per patch in the rebase template, but in this case subject spills over to the next line which rebase mistakes for an instruction:
error: unknown instruction action `certain`
Fix this my replacing new lines and line feeds in the subject with spaces.

fix: harden "stg rebase -i" against patches with milti-line subjects

---

src/cmd/fold.rs
src/cmd/import.rs
src/stupid/context.rs
t/t1800-import.sh
t/t1800/diff-with-rejects
t/t3600-fold.sh

When trying to import a patch that does not apply cleanly, and using --reject option, stg should apply what it can, leave the rest in .rej files, and create an empty commit. The work to apply the patch is outsourced to "git apply --reject" which exits with status code 1 if patch is applied partially and it is treated as error by stg import.
Fix the issue by not treating return code of 1 from "git apply" as an error when "--reject" option is specified, but rather saving its output, printing it for the user, and continuing with the rest of the import logic. Exit with CONFLICT_ERROR rather than COMMAND_ERROR when the patch does not import/apply cleanly.
"stg fold" reuses much of the same code so it has to be adjusted in the similar fashion. It will also exit with CONFLICT_ERROR when a patch …

fix: stg import --reject should create empty commit

---

src/cmd/rebase.rs
t/t2200-rebase.sh
t/test-lib-functions.sh

When calling "git rebase" without a target commit argument then it will try to look up remote tracking branch and rebase onto that. This change makes "stg rebase" behave the same way. Note that this introduces a slight discrepancy with "stg rebase --interactive": in this case it will still use the stack base instead of the remote tracking branch.

support calling stg rebase without arguments

---

src/patch/offset.rs

Fix an unused import warning caused by a repeated `use winnow::Parser;` statement.

chore: fix warning

---

src/cmd/completion/list.rs
src/cmd/mod.rs
src/main.rs

The list of subcommands is getting rather long. Combined with aliases they create a wall of text in the help message that is hard to scan. We can break up the long list into multiple smallers by grouping commands by category. This creates a more meaningful help message.
```
Compiling stgit v2.4.13 (/Users/frank/Projects/stgit)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.82s
Running `target/debug/stg`
Maintain a stack of patches on top of a Git branch.
Usage: stg [OPTIONS] <command> [...]
stg [OPTIONS] <-h|--help>
stg --version
Commands:
branch      Branch operations: switch, list, create, rename, delete, ...
clean       Delete empty patches from the series
commit      Finalize patches to the stack base
completion  Support for shell completions
delete      Delete …
```

feat: organize subcommands by group in help

---

src/cmd/mod.rs
src/cmd/name.rs
t/t3700-name.sh

Add a "stg name" command that works like "stg id" but returns the patch name instead of the revision. This can be useful for scripting and some command aliases.
I often use this like this to update PRs:
```
git push fbenkstein +$(stg id 0):refs/heads/$(stg name 0)
```
This is a generalization of the "stg next" command: "stg next" is now (almost) equivalent to "stg name +1".

feat: new "name" subcommand

---

CONTRIBUTING.md
Documentation/stg.txt

After reading the documentation to `stgit.autosign` I set it to `true` and got a trailer like `true: My Name <my@email.net>` which wasn't what I expected. I reworded the documentation slightly which hopefully clarifies it a bit. I also added a hint to `CONTRIBUTING.md` which I hope is the right thing.

docs: explain stgit.autosign a bit better

---

.github/workflows/ci.yml

Explicitly move to ubuntu-24.04 images, which will soon become ubuntu-latest for github actions.
Ref: https://github.com/actions/runner-images/issues/10636
Ref: https://github.com/actions/runner-images/blob/main/README.md

ci: use ubuntu-24.04 image

---

.github/workflows/ci.yml
INSTALL.md
Makefile

Now that the riscv64gc musl target is promoted to tier2 and everything is in place, let's build for riscv64
Debian package tested on real HW.

build: statically linked packages for riscv64

---

contrib/stgit.el

Hello!  Back again with another round of improvements!
A notable improvement is "Allow empty descriptions" as that was causing spurious and frustrating errors while trying to use it.
Admittedly most of this (6 out of the 8 commits) is just satiating the compiler and should hopefully not cause any changes whatsoever.
Locally testing these changes seems to work but due to a lack of a test suite and the fact that I don't personally use every available code path here, there is a decent chance I broke something somewhere.

stgit.el improvements #2

---

src/cmd/version.rs

docs: Update copyright year
